export const TeamInfo = {
  'Anaheim Ducks': {
    id: 24, 
    city: 'Anaheim',
    abbreviation: 'ANA',
    conference: 'Western',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/ana.png',
    pColor: '#F47A38',
    sColor: '#B9975B',
  },
  'Arizona Coyotes': {
    id: 53, 
    city: 'Glendale',
    abbreviation: 'ARI',
    conference: 'Western',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/ari.png',
    pColor: '#8C2633',
    sColor: '#e2d6b5',
  },
  'Boston Bruins': {
    id: 6, 
    city: 'Boston',
    abbreviation: 'BOS',
    conference: 'Eastern',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/bos.png',
    pColor: '#FFB81C',
    sColor: '#000000',
  },
  'Buffalo Sabres': {
    id: 7, 
    city: 'Buffalo',
    abbreviation: 'BUF',
    conference: 'Eastern',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/buf.png',
    pColor: '#002654',
    sColor: '#FCB514',
  },
  'Calgary Flames': {
    id: 20, 
    city: 'Calgary',
    abbreviation: 'CGY',
    conference: 'Western',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/cgy.png',
    pColor: '#c8102E',
    sColor: '#F1BE48',
  },
  'Carolina Hurricanes': {
    id: 12, 
    city: 'Raleigh',
    abbreviation: 'CAR',
    conference: 'Eastern',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/car.png',
    pColor: '#cc0000',
    sColor: '#000000',
  },
  'Chicago Blackhawks': {
    id: 16, 
    city: 'Chicago',
    abbreviation: 'CHI',
    conference: 'Eastern',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/chi.png',
    pColor: '#CF0A2C',
    sColor: '#FF671B',
  },
  'Colorado Avalanche': {
    id: 21, 
    city: 'Denver',
    abbreviation: 'COL',
    conference: 'Western',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/col.png',
    pColor: '#6F263D',
    sColor: '#236192',
  },
  'Columbus Blue Jackets': {
    id: 29, 
    city: 'Columbus',
    abbreviation: 'CBJ',
    conference: 'Western',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/cbj.png',
    pColor: '#002654',
    sColor: '#ce1126',
  },
  'Dallas Stars': {
    id: 25, 
    city: 'Dallas',
    abbreviation: 'DAL',
    conference: 'Western',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/dal.png',
    pColor: '#006847',
    sColor: '#8F8F8C',
  },
  'Detroit Red Wings': {
    id: 17, 
    city: 'Detroit',
    abbreviation: 'DET',
    conference: 'Eastern',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/det.png',
    pColor: '#ce1126',
    sColor: '#FFFFFF',
  },
  'Edmonton Oilers': {
    id: 22, 
    city: 'Edmonton',
    abbreviation: 'EDM',
    conference: 'Western',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/edm.png',
    pColor: '#041E42',
    sColor: '#FF4C00',
  },
  'Florida Panthers': {
    id: 13, 
    city: 'Sunrise',
    abbreviation: 'FLA',
    conference: 'Eastern',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/fla.png',
    pColor: '#041E42',
    sColor: '#c8102E',
  },
  'Los Angeles Kings': {
    id: 26, 
    city: 'Los Angeles',
    abbreviation: 'LAK',
    conference: 'Western',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/la.png',
    pColor: '#111111',
    sColor: '#A2AAAD',
  },
  'Minnesota Wild': {
    id: 30, 
    city: 'St. Paul',
    abbreviation: 'MIN',
    conference: 'Western',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/min.png',
    pColor: '#A6192E',
    sColor: '#154734',
  },
  'Montréal Canadiens': {
    id: 8, 
    city: 'Montréal',
    abbreviation: 'MTL',
    conference: 'Eastern',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/mtl.png',
    pColor: '#AF1E2D',
    sColor: '#192168',
  },
  'Nashville Predators': {
    id: 18, 
    city: 'Nashville',
    abbreviation: 'NSH',
    conference: 'Western',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/nsh.png',
    pColor: '#FFB81C',
    sColor: '#041E42',
  },
  'New Jersey Devils': {
    id: 1, 
    city: 'Newark',
    abbreviation: 'NJD',
    conference: 'Eastern',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/njd.png',
    pColor: '#CE1126',
    sColor: '#000000',
  },
  'New York Islanders': {
    id: 2, 
    city: 'Uniondale',
    abbreviation: 'NYI',
    conference: 'Eastern',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/nyi.png',
    pColor: '#00539b',
    sColor: '#f47d30',
  },
  'New York Rangers': {
    id: 3, 
    city: 'New York',
    abbreviation: 'NYR',
    conference: 'Eastern',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/nyr.png',
    pColor: '#0038A8',
    sColor: '#CE1126',
  },
  'Ottawa Senators': {
    id: 9, 
    city: 'Ottawa',
    abbreviation: 'OTT',
    conference: 'Eastern',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/ott.png',
    pColor: '#c52032',
    sColor: '#C2912C',
  },
  'Philadelphia Flyers': {
    id: 4, 
    city: 'Philadelphia',
    abbreviation: 'PHI',
    conference: 'Eastern',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/phi.png',
    pColor: '#F74902',
    sColor: '#000000',
  },
  'Pittsburgh Penguins': {
    id: 5, 
    city: 'Pittsburgh',
    abbreviation: 'PIT',
    conference: 'Eastern',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/pit.png',
    pColor: '#000000',
    sColor: '#CFC493',
  },
  'St. Louis Blues': {
    id: 19, 
    city: 'St. Louis',
    abbreviation: 'STL',
    conference: 'Western',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/stl.png',
    pColor: '#002F87',
    sColor: '#FCB514',
  },
  'San Jose Sharks': {
    id: 28, 
    city: 'San Jose',
    abbreviation: 'SJS',
    conference: 'Western',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/sj.png',
    pColor: '#006D75',
    sColor: '#EA7200',
  },
  'Seattle Kraken': {
    id: 55, 
    city: 'Seattle',
    abbreviation: 'SEA',
    conference: 'Western',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/sea.png',
    pColor: '#001628',
    sColor: '#99d9d9',
  },
  'Tampa Bay Lightning': {
    id: 14, 
    city: 'Tampa',
    abbreviation: 'TBL',
    conference: 'Eastern',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/tb.png',
    pColor: '#002868',
    sColor: '#FFFFFF',
  },
  'Toronto Maple Leafs': {
    id: 10, 
    city: 'Toronto',
    abbreviation: 'TOR',
    conference: 'Eastern',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/tor.png',
    pColor: '#00205b',
    sColor: '#FFFFFF',
  },
  'Vancouver Canucks': {
    id: 23, 
    city: 'Vancouver',
    abbreviation: 'VAN',
    conference: 'Western',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/van.png',
    pColor: '#00205B',
    sColor: '#00843d',
  },
  'Vegas Golden Knights': {
    id: 54, 
    city: 'Las Vegas',
    abbreviation: 'VGK',
    conference: 'Western',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/vgs.png',
    pColor: '#B4975A',
    sColor: '#333f42',
  },
  'Washington Capitals': {
    id: 15, 
    city: 'Washington',
    abbreviation: 'WSH',
    conference: 'Eastern',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/wsh.png',
    pColor: '#041E42',
    sColor: '#C8102E',
  },
  'Winnipeg Jets': {
    id: 52, 
    city: 'Winnipeg',
    abbreviation: 'WPG',
    conference: 'Western',
    logo: 'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nhl/500/wpg.png',
    pColor: '#041E42',
    sColor: '#004C97',
  },
}